// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFjywvICRbdFH6NPxIyRA1nMoxLYUx9k',
    appId: '1:238353162029:web:559a145952996f80f27da4',
    messagingSenderId: '238353162029',
    projectId: 'mcq-quiz-app-b205f',
    authDomain: 'mcq-quiz-app-b205f.firebaseapp.com',
    storageBucket: 'mcq-quiz-app-b205f.appspot.com',
    measurementId: 'G-L65WZDRNM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQpfBQ9diwzfXr6G7RZjjVBmAnTZse4i0',
    appId: '1:238353162029:android:04d8cd03daf830e6f27da4',
    messagingSenderId: '238353162029',
    projectId: 'mcq-quiz-app-b205f',
    storageBucket: 'mcq-quiz-app-b205f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2r2e225DJ750m3AGLSj3joG5Osu_iD9s',
    appId: '1:238353162029:ios:f212d62ae8ecb66df27da4',
    messagingSenderId: '238353162029',
    projectId: 'mcq-quiz-app-b205f',
    storageBucket: 'mcq-quiz-app-b205f.appspot.com',
    iosBundleId: 'com.example.mcqQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2r2e225DJ750m3AGLSj3joG5Osu_iD9s',
    appId: '1:238353162029:ios:f212d62ae8ecb66df27da4',
    messagingSenderId: '238353162029',
    projectId: 'mcq-quiz-app-b205f',
    storageBucket: 'mcq-quiz-app-b205f.appspot.com',
    iosBundleId: 'com.example.mcqQuiz',
  );
}
